### ISSUE TITLE
Error injecting glassmask

### ISSUE THREAD

**Issue by HonestySoftware** [shalzuth/BraveHaxvius#11]
Not sure if it affects other items as well, since I didn't try yet, but getting an error trying to inject glass mask. 

`            b.DoMission(Mission.AirshipDeck, false, null, "20:" + Equipment.GlassMask.EquipId + ":1");
            b.DoMission(Mission.AirshipDeck);`

[Error Picture](https://media.discordapp.net/attachments/368524064492617750/370623405223051274/unknown.png?width=952&height=464)

Worked fine for Reaver.

**Comment by HonestySoftware** [comment]
Probably only event items from GlassMask to CloakofFlames having issues with injection. Worked fine for everything else.

Thanks for your hard work

**Comment by shalzuth** [comment]
Seems like a server bug that we can't inject it.
FYI equipment is 21 (not 20), it doesn't matter from an injection standpoint though.
