### ISSUE TITLE
Selling items after using rank up

### ISSUE THREAD

**Issue by RiboRino** [shalzuth/BraveHaxvius#12]
Could you consider implementing this?

**Comment by shalzuth** [comment]
Sell which items? Not sure I follow.

**Comment by RiboRino** [comment]
Items dropped/stolen from Port City Lodin. 
Example:
Enemy dropped item : Beast Meat : 1
Enemy dropped item : Crimson Tear : 2
Enemy stolen item : Beast Meat : 3
Enemy stolen item : Life Orb : 3
Enemy stolen item : Crimson Tear : 3
Enemy stolen item : Quality Parts : 3
Enemy stolen item : Chromatic Ooze : 3

Maybe every rank up you sell off the items? Otherwise you end up with 1000s of these.

**Comment by shalzuth** [comment]
Ah yes need to turn off collect loot
