### ISSUE TITLE
Using unlinked account info on the android app

### ISSUE THREAD

**Issue by RiboRino** [shalzuth/BraveHaxvius#17]
Using ReRoll() to get unlinked account info is there a way to use this info to login on the android app or is the info only usable via BraveHaxvius?

**Comment by shalzuth** [comment]
Yes

**Comment by RiboRino** [comment]
Do you know what file has that info?

**Comment by WithinGDR** [comment]
I'm also curious about this too. Within auth.xml is the UserID and Password. Then separated by a comma is what I assume the Gumi ID and Token. Plugging in the info from the accounts file results in the app continuously saying please login again. Plugging in a new account info from auth.xml to BraveHaxvius result in an error saying that it can't find the User ID after doing updategetinfo but, if the account was created with BraveHaxvius then it works. Auth.xml might not even contain the gid and Token or maybe BraveHaxvius isn't set up yet for this kind of thing, I've honestly no idea.

**Comment by shalzuth** [comment]
WithinGDR is on the right track...
Rerolled accounts are locked to an OS. Need to change it to Android before running ReRoll account.

**Comment by WithinGDR** [comment]
Wow i'm an idiot. Thanks shalzuth

**Comment by RiboRino** [comment]
TY for help i got it
