### ISSUE TITLE
JP Login issue

### ISSUE THREAD

**Issue by HonestySoftware** [shalzuth/BraveHaxvius#19]
After updating from commit 8fb7c09... to 2c2809e... I can't login into my JP account anymore. Right after pressing "login" to retrieve banners getting the listed error below.
Before I got the same message over and over trying to use the summon function. 

Global login and function still work fine on the other side.

[Error](https://media.discordapp.net/attachments/349772219875983360/371642908585099264/unknown.png)

Edit: Same issue with the release / .exe version (crashes there)

**Comment by shalzuth** [comment]
https://github.com/shalzuth/BraveHaxvius/commit/ce6e863c01e0fe2f3afcf1e6ab1676e1a1f9413d
Fixed in this release I think.

**Comment by SupremeNooblet** [comment]
Hi there, whenever I try to login with my JP accounts to perform summons. The program keeps crashing.

**Comment by HonestySoftware** [comment]
Login seems to be fixed but still issues with pulling / summoning. Tried various banners but it throws same error as before with login.

[Error](https://i.imgur.com/ri6Wz4V.png)

**Comment by raklaron** [comment]
Hello. I'm trying to enter JP, but i seem to have the same error i got before (i got v. 1.0.28).

![](https://cdn.discordapp.com/attachments/369233747989757954/371962091013275649/unknown.png)

I double-checked my pins, internet and downloaded files.
