### ISSUE TITLE
FuckAccount()

### ISSUE THREAD

**Issue by WithinGDR** [shalzuth/BraveHaxvius#20]
So..uh.. I messed up an equipment injection and accidentally injected 1,401,001,500 Raven Berets. This causes the FFBE app to crash if you look at equipment under the items menu or if you tap on the head gear equipment box on the unit screen. If FuckAccount() is used to Fuck an account then this would be a method.

**Comment by shalzuth** [comment]
https://github.com/shalzuth/BraveHaxvius/commit/ce6e863c01e0fe2f3afcf1e6ab1676e1a1f9413d
Can sell those items, but might need to in segments (not all at once). Fixed in latest.
