### ISSUE TITLE
newbie guide

### ISSUE THREAD

**Issue by McDohI** [shalzuth/BraveHaxvius#21]
sorry im really newbie on this but im trying hard to learn
i just download fiddler and stuck there, i dont know how to operate it neither how to open ur repository, is it via fiddler or else?
and should i use emulator to hack?
so blur to me
, really thank if u have youtube tutorial

**Comment by ChrisLHY** [comment]
Thank you very much for working on this project guys, I really appreciate it. I am on the same boat as McDohl - I got stuck after installing fiddler. It would be really great if we can get more instructions e.g. step 1 click this, step 2 click that etc.

**Comment by HonestySoftware** [comment]
If you don't know anything about coding / reverse engineering, don't bother with it. 

https://github.com/shalzuth/BraveHaxvius/releases

go there and download zip file. Everything else should be self explainable.

**Comment by ChrisLHY** [comment]
Thanks a lot HonestySoftware. It works like a charm!

Just a minor question - do you know if there is a way to inject pots? Many thanks.

**Comment by JNS1984** [comment]
Okay, I think I am doing something wrong. I downloaded the repository and tried starting the bravehaxvius.exe. but well it always crashes. anyone any idea?

**Comment by firefist8** [comment]
can any1 help me with the proxy setting. I think I am doing something wrong.

**Comment by JNS1984** [comment]
It always crashes when it tries to create a user. U am trying to get it to work but I don't even know where to start...

**Comment by OGVENDETTA** [comment]
@JNS1984 
Play the game first to create user.
@firefist8 
What is the error? Please be specific.

**Comment by JNS1984** [comment]
@OGVENDETTA
I already have an account. It's also maxed. That is why I am stumped. I use FB ID and Token. And fiddler Proxy. The 1st 2 intiallations send and get an answer but on the third one "create user" the exe crashes. So I don't know what I am doing wrong.

**Comment by firefist8** [comment]
@OGVENDETTA  I dont know what to enter in the proxy ip and port. I am a complete noob at this. Please help

**Comment by shalzuth** [comment]
@JNS1984 if it's saying "create user", your id/token are incorrect (or it's a new account).
@firefist8 leave proxy blank.

**Comment by JNS1984** [comment]
@shalzuth Thank you. My FB ID was wrong. Now it works like a charm.

**Comment by bob548** [comment]
Can someone show me an example of what their program.cs page looks like? I have my Facebook token and ID in, and I know the token is right otherwise I wouldn't have been able to get the ID. I'm lost here guys.

**Comment by evascyphis** [comment]
does anyone can guide me how to or instruction to use this tool?
thank you in advance
