### ISSUE TITLE
Can items be deleted?

### ISSUE THREAD

**Issue by helloffbeworld1** [shalzuth/BraveHaxvius#22]
Hi,

Is there a way to delete items?  Like if we accidentally type in too many of an item (like 200k+), is there a way in the program to delete them? ie: if we enter -9999 and inject, will this remove it?
 
Or is there another way?  Thanks

**Comment by shalzuth** [comment]
Sell them. The client app has a sell tab.

**Comment by helloffbeworld1** [comment]
Thanks Shal!  I tried to use, but when I enter in a number; ie:  if i specify 200000 for the 10+1 tickets, the program always crashes

**Comment by helloffbeworld1** [comment]
ooh nvm.  please ignore.  I figured it out.  Thank you Shal!
