### ISSUE TITLE
JP cannot login

### ISSUE THREAD

**Issue by Cybotor** [shalzuth/BraveHaxvius#27]
It's always crash after login

**Comment by raklaron** [comment]
I can login and can summon but the not %100 of the time. Sometimes i can summon like 5 times consecutively, and sometimes i cannot summon for like 10-20 tries.

For the record, i'm using 50106 and 3* (sometimes 4* works too).

**Comment by Cybotor** [comment]
@raklaron I've try both release 1.0.34 and recompile. but all cannot login.
application always crash.
does it need anything special (I ran on Win10)

**Comment by raklaron** [comment]
I cannot login to JP now, so i think it wont work, at least for now.

**Comment by Cybotor** [comment]
I can login now, it's my bad to miss-understood on UI >_<
I put id/pw on banner-list box
