### ISSUE TITLE
Unit Hunter without locking 3* and 4*

### ISSUE THREAD

**Issue by tommygirl** [shalzuth/BraveHaxvius#28]
Hi, is it possible to have the unit hunter function without it locking 3* and 4* units in the game when the 'Sell 3*' and 'Sell 4*' are de-selected?

**Comment by WithinGDR** [comment]
You can use UnfavoriteAll() to get rid of the locks

**Comment by DyWaBeng** [comment]
the unit hunter was working but now it crashes on me. is there anything that i have done wrong? thanks for your time

**Comment by TetoraK** [comment]
No tickets?

**Comment by danzkimon** [comment]
"You can use UnfavoriteAll() to get rid of the locks" how to do this?

**Comment by shalzuth** [comment]
Unit hunter only works if you have 10+1 tickets leftover from injection.
