### ISSUE TITLE
can JP summon more than 11 unit / ticket?

### ISSUE THREAD

**Issue by Cybotor** [shalzuth/BraveHaxvius#33]
As test, now JP summon can use for do 11 units summon on some banner and only 3* and 4* ticket.
(5* ex is can done on EX banner and get only 1 unit)

how possible to summon more than 11 unit on 1 ticket?

**Comment by OscarCox** [comment]
you can try 5* ex on other banners , will get 11 x 5* .

**Comment by JunkyardCat** [comment]
how do you guys do that? when i summon it stops at gachaexe then it crashes

**Comment by Cybotor** [comment]
@JunkyardCat make sure that you really have ticket.

**Comment by JunkyardCat** [comment]
@Cybotor thanks. do you happen to know how unit hunter work?

**Comment by firefist8** [comment]
What ticket is the one labeled as "??" in the list of ticket to choose from when you try to summon?

**Comment by Cybotor** [comment]
@firefist8  ?? is ticket id no "3", It's may some special ticket that not release yet or passed-away
