### ISSUE TITLE
How to update data?

### ISSUE THREAD

**Issue by Cybotor** [shalzuth/BraveHaxvius#35]
As I check current updated data by @OGVENDETTA , I think you're focus on GL while JP data still not.
Could you guide me how to extract data from JP side?

**Comment by OGVENDETTA** [comment]
This is for global. Unfortunately none of the tools or resources here will help you extract data from the JP side. You would have to seek assistance else where.

**Comment by Cybotor** [comment]
@OGVENDETTA  Thanks for your mention.
