### ISSUE TITLE
How to find AppVersion, RscVersion, MstVersion?

### ISSUE THREAD

**Issue by Cybotor** [shalzuth/BraveHaxvius#39]
I try to review the code to mod for JP use.
I found these variable [AppVersion, RscVersion, MstVersion]
I'm not sure it's up to date or not and how to find them

@serenitygrant  @OGVENDETTA  or anyone can you guide me?

**Comment by hantucloud** [comment]
check with packetdecoder, 
if you want to check with ur phone or emulator 
you must same network, ex wifi setting http proxy to your ip packetdecoder ... or try to check raw data with fiddler

**Comment by Cybotor** [comment]
Thank you, I got it and mod the program.
for JP ver now the data are
AppVersion = 1032
RscVersion = 664
MstVersion = 1943
