### ISSUE TITLE
Cannot Run Data Extractor

### ISSUE THREAD

**Issue by HotMoogle** [shalzuth/BraveHaxvius#43]
Error at /dataExtractor/program.cs line 350

Sequence Contains no Matching Element

**Comment by Cybotor** [comment]
Change AppVersion to _1030_ and BuildVersion to _2.4.1_
Then rebuild program.

**Comment by HotMoogle** [comment]
hi @Cybotor  is that for global setting? sorry im not on my pc atm

**Comment by HotMoogle** [comment]
last question and thanks for the help

how to see AppVersion and BuildVersion every patch? thanks a lot its a great help for my learning

**Comment by Cybotor** [comment]
@HotMoogle  Yes, above Version_no. is for GL setting
you can use PacketDecoder to catch send/return packet. It's contain needed information
**_AppVersion, RscVerson, MstVersion_**
For **_BuildVersion_** you can see as application version on Title Screen.

check this for my previous question about how to find these information >> https://github.com/shalzuth/BraveHaxvius/issues/39

**Comment by HotMoogle** [comment]
@Cybotor hmm after changing those variables i got the challenge.cs errors now. what im doing wrong? can enlighten me a bit? 

Thanks and regards, i just want to update it and run dataextractor

**Comment by Cybotor** [comment]
I just done change on only 1 file
"BraveExvius.cs" line no.
16 - public String AppVersion { get; set; } = "1030";
18 - public String MstVersion { get; set; } = "1013";
25 - public String BuildVersion { get { return Locale == "JP" ? "ver.3.0.1" : "ver.2.4.1"; } }

after Built Solution, I can run without any error.

**Comment by HotMoogle** [comment]
@Cybotor  isee true no errors but if you ran dataextractor then recompile gives errors

**Comment by HotMoogle** [comment]
btw dataextractor updates all tables vendetta mentioned that wait for the dos to close before recompiling for complete update

**Comment by Cybotor** [comment]
I mean no error both compile and run DataExtractor.
I'm also modify shalzuth to update new resource as below 

![haxvius](https://user-images.githubusercontent.com/33109613/32313265-99170b94-bfd4-11e7-8a0e-be9d3689a7b2.PNG)


anyway I can give all update resource from here

https://www.dropbox.com/s/h9wecek1nhcwf31/Data.rar?dl=0

_ps. all was done on Visual Studio 2015_

**Comment by HotMoogle** [comment]
ayt its now working i  just replaced the challenge.cs with the old one, for jp let me try in an hour brb need to locate which site jpn downloads the data ill get back here

**Comment by Cybotor** [comment]
I also need JPN download site also.
If you know any information, please let me know

now I try to work on 
- JPN download data.
- How to do summon more then 11 unit per ticket
... but still not have any clue. >_<

**Comment by HotMoogle** [comment]
@Cybotor ok im trying to crack the code now. all the http servers i input was all error and returned 404 haha ill let you know once i have the progress

**Comment by HotMoogle** [comment]
@Cybotor cdn.resource.exvius.com/lapis/resource <<<< but we need to crack open the encryption to enter the DB <found it by disassembling the app using IDA>

**Comment by JunkyardCat** [comment]
@Cybotor how did you get the id for the jp materia and equips and items thats not in the current release

**Comment by Cybotor** [comment]
@JunkyardCat Run data extractor to retrieve new data from update
then compile program again to include new data to program.

**Comment by jkardoza** [comment]
@Cybotor how can create this interface ?

**Comment by Mikeo73** [comment]
Anyone know the ID # of the new king mog item in JP?

**Comment by Cybotor** [comment]
@jkardoza  I just modify data-grid to include item description, for other not change core program from @shalzuth 

@Mikeo73 still cannot extract data from JPN side >_<

**Comment by jkardoza** [comment]
@Cybotor you can do a tutorial? hard for me

**Comment by firefist8** [comment]
@Cybotor can you please share your modified program with us. I am a total noob so don't know where to start.

**Comment by Mikeo73** [comment]
@Cybotor I started doing the same thing, but yes I also couldn't get jp data to extract. I'll post what I did if I get it working.

**Comment by Cybotor** [comment]
Here is my modified
https://www.dropbox.com/s/beqki7g0az3xy74/BraveHaxvius.rar?dl=0
so sorry I don't know how to update to github repository.

Change are:
- Change version both GL & JP
- add JName on Injection tab
- update equip, item, material from latest GL update

you need to re-compile/rebuilt by yourself by Visual Studio (2015 or 2017 are fine).
I ever try to build, but cannot run on another PC, and dunno why.


@jkardoza For tutorial, so sorry I don't know how to start.
I also learn for C# from google and youtube, it's better to try by yourself.
I not yet a programmer, just can read and modify some code.

**Comment by Cybotor** [comment]
@HotMoogle  could you try 
http://cdnbase.resource.exvius.com/lapis/resource/

I try but got some error on MST variable 
Not sure from code or not, because original code is for GL.
It's may some variable  or operation not not match with JP

**Comment by Leon1080** [comment]
@Cybotor hope you can extract jp data
Thank for your resource

**Comment by jkardoza** [comment]
@cybotor you can use bot to farming in last patche?

**Comment by HotMoogle** [comment]
Please nake a new thread thank you
