### ISSUE TITLE
GL injection not working

### ISSUE THREAD

**Issue by HotMoogle** [shalzuth/BraveHaxvius#48]
Global.

**Comment by hantucloud** [comment]
just do little modification , its works again.

**Comment by jash1412** [comment]
@hantucloud can you please share the steps on how to do the necessary modification? I have managed to get Fiddler working, but I am not sure how to find out the packet to analyse and get the necessary AppVersion, RscVersion, MstVersion and BuildVersion.

Or can you share your working files? Thank you.

**Comment by Cybotor** [comment]
current version
JP: 
  app=1032, rsc=677, mst=1985

GL: (will change again today)
  app=1030, rsc=0, mst=1017 
  change server address on networking.cs from _lapisv230 .gumi**_ to _lapis-prod.gumi.sg**_

**Comment by HotMoogle** [comment]
Haha earlier i thought its not working theres just something on facebook anyway @cybotor did you manage to extract jp now? I got some errors yet need to find these values

**Comment by HotMoogle** [comment]
MST 1032 Global

**Comment by Cybotor** [comment]
Still cannot find out master data address.
>_<

**Comment by donradzsk** [comment]
I'm using Visual Studio Enterprise and getting this error trying to TM farm:
![haxv000](https://user-images.githubusercontent.com/33736714/32925727-6c029aae-cb11-11e7-861a-54a68409eff8.jpg)
Is there a fix?

**Comment by Cybotor** [comment]
@HotMoogle 
http://cdn.resource.exvius.com/lapis/resource/mst/Ver308_7FGj2bCh.dat

**Comment by robidk** [comment]
Hi,

Is the MST 1032 or is that the AppVersion?

Also I have got charlesproxy setup to read the packets, can anyone point me in direction of how to get the AppVersion/MST version, is it part of a header message or do I need to look out for a specific message. From what I saw so far all I was seeing was the version number and no reference to MST or App.

**Comment by aurreal** [comment]
@Cybotor http://cdn.resource.exvius.com/lapis/resource/mst/Ver308_7FGj2bCh.dat << this is for jp database? where should i put it? on networking.cs?

**Comment by Cybotor** [comment]
@aurreal just raw file.
I cannot extract it yet.

**Comment by dominic-codespoti** [comment]
@Cybotor Hey! Can you explain as to how you get the AppVersion, RscVersion, MstVersion and BuildVersion? I have Fiddler up and running however I am unable to decrypt the packets to find any important details.

**Comment by hantucloud** [comment]
@thed24 i use iphone, connect same wifi then use PacketDecoder project...
to see new version info

**Comment by thed24** [comment]
@hantucloud could you link me to the program?

**Comment by dominic-codespoti** [comment]
@hantucloud what modifications did you make to get it working?

**Comment by hantucloud** [comment]
@thed24 at BraveExvius project modify ur app version mst version or rsc... then use DataExtractor to refresh ur gamedatabase like ur Mission data etc..
this tools is great for education to sniffing packet data

**Comment by dominic-codespoti** [comment]
@hantucloud Yeah it is! I've learnt a good bit, i've done all that however my program crashes when attempting to summon units in JP!

**Comment by hantucloud** [comment]
@thed24 i dont play JP, you can trace by PacketDecoder or error debug on Visual Studio.

**Comment by robidk** [comment]
Anyone know if complete missions can be enabled? and does it work? i.e use magic, esper etc or defeat boss with lb?

**Comment by dinhlehuynh** [comment]
![new bitmap image 2](https://user-images.githubusercontent.com/32948385/32996036-e5c5d0cc-cdaf-11e7-9aa4-3ad1d7aca17c.jpg)
Same with @donradzsk , 

Updated the Network.cs and BraveExvius.cs.....like @Cybotor guide.. but still not working, pls help....

**Comment by Cybotor** [comment]
@dinhlehuynh @donradzsk 
I'm not sure about this error. But similar with error I found when do data-extractor.
It's maybe file unit.cs was corrupted. (Haxvius\data)
try to replace with @shalzuth original file and re-compile.

if this cannot help .... I dunno to solve this heh.

**Comment by HotMoogle** [comment]
@Cybotor help me to run those 3 Python IDA Files for extraction , i guess this is the key to our problem.
If you want IDA i can share mine just ask me, those 3 py files are very interesting

**Comment by HotMoogle** [comment]
@Cybotor nevermind what i said earlier,
i was wondering if i can catch the packets using my phone and using the packet decoder.
if so how can it be done?

**Comment by hantucloud** [comment]
@HotMoogle 
![2017-11-20_170939](https://user-images.githubusercontent.com/11237395/33013179-ae1cbddc-ce15-11e7-9f73-4b640af0db45.jpg)

**Comment by jash1412** [comment]
@hantucloud WOW..!! that looks nice. do you mind to share the source file? Thanks.

**Comment by HotMoogle** [comment]
@hantucloud haha yeah any other method than running those 2? i mean like example use your phone and the packet decoder.. and can catch the packets

**Comment by HotMoogle** [comment]
@hantucloud @Cybotor anyone of you fixed the exploration loot? there seems error upon running one, im updating the achievement (challenges) will share soon..

**Comment by HotMoogle** [comment]
MSt 1039 Global

**Comment by Cybotor** [comment]
Exploration run fine, at least last sunday before update.
But I only do on Enchanted Maze.

Regard to Milla’s tool experience. 
Done exploration on story  it’s may ruin your game.
Coz you will take all key items before quest. And it (may) made you cannot clear that quest forever.

**Comment by robidk** [comment]
@Cybotor  can we use the packet decoder to intercept quest completion packets  and then replicate  it using different mission ids to auto complete the quests? 
So far I have only seen packet decoder working whilst using this client. Do I need to accept and install the certificate when running packet decoder to view packets from phone/emulators etc?

**Comment by Cybotor** [comment]
@robidk technically is yes (for capture data)
but I never try before coz I don't know how to install certificate to phone/emulator. lol

but you can as you mention by run mission tab original by @shalzuth .
all mission order by story line. (at lease for GL update).

**Comment by hantucloud** [comment]
@robidk yes you can modif packet using packet decoder.

@HotMoogle okay i will share configuration using my phone (iphone) because Android version has Zip Encoding

@jash1412 sure next time i will share my project by external link because im removed all JP configuration
i have added several feature like auto clear raid colo and event so you can afk hehe
and view current timer lvl etc but only for Global.

**Comment by dominic-codespoti** [comment]
@hantucloud Your program version looks so cool!

**Comment by HotMoogle** [comment]
@hantucloud haha nice , got some bad news about challenge mode, thats why shalzuth never activated the button for challenge mission its not working, i tried re coding it for the same logic as trophies but failed, no achievement is done 

@hantucloud and yeah if ever you share your program upload it in a day then delete it :D avoid leaks

**Comment by donradzsk** [comment]
Did the app version for global change?

**Comment by ggwpx** [comment]
I have fiddler and FFBE packet decoder open but FFBE packet decoder is not receiving anything...

**Comment by hantucloud** [comment]
here my project [BraveHaxvius.zip](https://github.com/shalzuth/BraveHaxvius/files/1501783/BraveHaxvius.zip)
but im sorry to say "i modify as i want!" :D 
- only for GL
- loggin only with gumi-id,gumi-token,id,pass,fb-id,fb-token you can search by using Packet Decoder at UserInfo packet
i only add 
+ change exception program to memo log
+ add auto clear event, arena, raid
+ you can see at func DoMission how i change FriendList to only select Event Unit or select specific item drop/stolen/found
+ you can see at ProjectDecoder how i modify RealTime packets (decrypt->change some data-> encrypt again)
+ add realtime ticks count energy and orbs to trigger Auto Clear funct
+ change at DataExtractor (i forget :p) but .cs has been added and modified.

all project are update with current game app,build,mst,etc...
ah please change Locale to ur spesific Country im using "ID" mwehehe

**Comment by Jhonvf20** [comment]
@hantucloud Wow! Cool! Thanks for your custom project! =D

**Comment by hantucloud** [comment]
@HotMoogle @Cybotor 

[bandicam 2017-11-24 21-07-55-872.zip](https://github.com/shalzuth/BraveHaxvius/files/1501865/bandicam.2017-11-24.21-07-55-872.zip)

here video tut to use PacketDecoder via IPhone
- make sure same network
- make sure ur firewall is "friendly" ;)

**Comment by newChallenger1** [comment]
sorry, OOT. @hantucloud whoa, are you Indonesian? Can I ask something? Where do you learn to code something like this?

**Comment by ggwpx** [comment]
when I ran inject, i got an error saying that Error : Failed to retrieve player name... also the Brave Haxvius.exe doesn't allow email/pw input.

**Comment by ggwpx** [comment]
@hantucloud  thanks for sharing. I appreciate your work.  I can't seem to get injection and unit summon working. I can login and get power leveling work though.  Any comments would be appreciated as I don't have any programming background.

**Comment by hantucloud** [comment]
@newChallenger1 yes iam indonesian, why ? 
just self improving i dont have a teacher.

@ggwpx im sorry my project only use for event hunter

**Comment by newChallenger1** [comment]
@hantucloud is your packetDecoder only for iPhone? I tried countless times and still not working in my android. Already installed the certificate, firewall allowing the program, but still nothing happen..

**Comment by hantucloud** [comment]
@newChallenger1 Android version has Zip Encoding, so you must catch with Fiddler and Decrypt manualy

**Comment by HotMoogle** [comment]
@hantucloud thanks i guess everyone has a copy kindly delete the uploaded files lets avoid you know spies and reporters :)

**Comment by HotMoogle** [comment]
Please Proceed to a New Issue i will file for updates! :) Thank you all

**Comment by mrbojoa** [comment]
Can someone share with me @hantucloud 's folder? I tried using v1.0.37 but it keeps on crashing :(

**Comment by HotMoogle** [comment]
#52

**Comment by Kyuuza** [comment]
hi anyone know what is the correct link to download jp assets in dataextractor,any chance a user is willing to share the updated repo mentioned above by @hantucloud thanks in advance

**Comment by Killer66** [comment]
@dinhlehuynh @donradzsk

The error is because you guys have a exclusive unit, maybe from a fan festa? I'm with the same error, but the unit is tinkerer carrie. Shes not in the units.cs file, so the error occurs. Someone can give me a updated unit.cs file?

**Comment by Killer66** [comment]
Nevermind, just figured out :D

**Comment by ActalNufofen** [comment]
@killer66 Can you share how did you resolve it? thanks.

**Comment by DregonYor** [comment]
could some one give me the code to add the MY ID tab , i want to add it to use event friend , thanks
