### ISSUE TITLE
Global and JP Update Thread!

### ISSUE THREAD

**Issue by HotMoogle** [shalzuth/BraveHaxvius#52]
Global 
APP 1033
RSC 0
MST 1052

JP: ( sorry i dont support jp aswell) if anyone knew please post

**Comment by dominic-codespoti** [comment]
Does the global injector work??

**Comment by Cybotor** [comment]
JP versions are 1033, 687, 2000

**Comment by HotMoogle** [comment]
@thed24  sorrybuddy injection doesnt work anymore on GL

**Comment by mrbojoa** [comment]
Hey @HotMoogle do you happen to have a working tool for TMR farming for GL? I was trying to use v1.0.37 but apparently it's not working well :(

**Comment by HotMoogle** [comment]
GL update:

MST 1058

:app keeps crushing running the farm bot:

every 10mins on my app :) but maybe its my isp

**Comment by Galentia** [comment]
It isn't your ISP. I'm getting connection errors as well.

**Comment by dinhlehuynh** [comment]
Same here, after update MST, the tool can run but after 5 mins and it got error.... any one find the way to fix?

**Comment by HotMoogle** [comment]
well i guess its gimu's server its stable now... no disconnects or whatever

**Comment by hantucloud** [comment]
@HotMoogle using try and catch to manipulate running function if got dc

**Comment by robidk** [comment]
Anyone manage to fix the challenges? I would have tried to catch packets and figure out what code is sent to complete which ones but I only have android/nox so cannot use the packet decoder :(

**Comment by HotMoogle** [comment]
GL 1061 :) 
@robidk  i tried to decode and make it work too but i stopped coz its too much for my little brain haha

**Comment by Ondraya** [comment]
have the numbers changed again?  I'm not getting it to connect.

**Comment by HotMoogle** [comment]
@ondraya 1066

**Comment by Leinadris** [comment]
Currently having some trouble with the data extractor, although it was working for the last few patches. Something to do with the F_SUBLIMATION_RECIPE_MST line, would anyone have any idea as to how to fix this?

**Comment by Ondraya** [comment]
Thank You!

**Comment by ggwpx** [comment]
does anyone know the code for automatically starting raid whenever the raidorb is at full?

**Comment by dsagaria** [comment]
I dont know how to update the bot.. someone can helpme with this?.. is there any guide?

**Comment by acexdt** [comment]
Newbie here.
May I ask how to find new versions for JP Android? 
I only found the GL version of Apple but I don't have an Apple device to try it on.

**Comment by Cybotor** [comment]
Locale = "JP";
AppVersion = "1034";
RscVersion = "713";
MstVersion = "2107";

summon still work fine on JP.
dangerous? ==> use at your own risk.

**Comment by HotMoogle** [comment]
GL - Build Version 2.5.0

**Comment by davidnenu** [comment]
global:
        public String AppVersion { get; set; } = "1034";
        public String RscVersion { get; set; } = "0";
        public String MstVersion { get; set; } = "1075";
;)

**Comment by tommygirl** [comment]
Hi totally new to VS here.. 
Updated in BraveExvius.cs to;
Locale = "JP";
AppVersion = "1034";
RscVersion = "713";
MstVersion = "2107";

Tried running airship from Testing-program.cs and encountered this error prompt. Any help?
![braveexvius](https://user-images.githubusercontent.com/33150891/34077602-96c7e656-e342-11e7-8f2e-34033ec64bb1.JPG)
![capture](https://user-images.githubusercontent.com/33150891/34077605-9c329582-e342-11e7-8a37-6f95be7d0a13.JPG)

**Comment by zalibi** [comment]
Crashing on the "CreateUser" command for JP. Global works fine. Did they update the version for JP again? Can't check myself. No iphone.

**Comment by Leinadris** [comment]
GL
New Build Ver - 2.5.1

**Comment by acexdt** [comment]
How do I find new versions for JP? help pls.

**Comment by Ondraya** [comment]
what are the new numbers?

**Comment by Ondraya** [comment]
more importantly, me being a complete noob at this stuff and self teaching, how do you go about figuring that out?

**Comment by Cybotor** [comment]
for JP
AppVersion = "1034";
RscVersion = "722";
MstVersion = "2132"

**Comment by dinhlehuynh** [comment]
Anyone know how to update the Tool while Exclusive units in Global came? tool got crash when I put new units to the team and run any maps...

**Comment by robidk** [comment]
You need to run the dataextractor.exe to update your data folder.

**Comment by zalibi** [comment]
Still getting crash on CreateUser. Weird.

**Comment by Killer66** [comment]
@robidk 

The exe on:   BraveHaxvius-master\DataExtractor\obj\Debug  ?

**Comment by Killer66** [comment]
Problem with  F_SUBLIMATION_RECIPE_MST, any hints?

**Comment by Killer66** [comment]
Nevermind, just figured out :D

**Comment by Tifw** [comment]
I'm crashing after "Get Userinfo". Started after the last patch, any ideas on how to fix?

**Comment by robidk** [comment]
I would guess that you need to check that you have correct versions and fb id/tokens.

**Comment by Tifw** [comment]
Well the FB ID/Tokens is still the same, but i don't know how to check if the version is the correct one. Well. i'll look into it.

**Comment by blackyuan2017** [comment]
Does injection work in global?

**Comment by zalibi** [comment]
Global MST has changed from 1075 to 1102 Tifw. Might be why you are crashing.

Still trying to figure out why I'm having trouble with JP. To be honest, I actually think its something to do with the info I'm using to log in... not sure what I'm doing wrong though.

**Comment by Tifw** [comment]
So, i re-downloaded every file again, but now i'm getting this message, something that didn't happen the first time.
![iwg2lulqq9eiyjhu247iag](https://user-images.githubusercontent.com/34791539/34322605-63809a0a-e80a-11e7-8e7a-4c6799799044.png)

**Comment by Killer66** [comment]
@blackyuan2017 
No.

**Comment by Killer66** [comment]
@Tifw , About that error on "get user info", it's probably because you have one of the new units. You can solve by updating the app, rsc and mst versions and after that, running dataextractor.

Lines 16, 17, 18:
public String AppVersion { get; set; } = "1034";
public String RscVersion { get; set; } = "0";
public String MstVersion { get; set; } = "1102";

line 25:
public String BuildVersion { get { return Locale == "JP" ? "ver.2.9.3" : "ver.2.5.1"; } }

Hope this helps.

**Comment by zalibi** [comment]
Ok. Almost got JP version to work. Now the problem is with the data extractor. It keeps failing referencing error 403(forbidden). Did they change the site address?

**Comment by Bazuzko** [comment]
I have the same problem as 'tommygirl' further up this thread.

I correctly updated the tool and extracted new data.

However now it seems the tool does not manage to connect to Facebook (see the picture: https://imgur.com/HI4ZD36).
To connect with the tool, I use email+password. I do not have the two-factor identification activated on my Facebook account. And this Facebook account is my real one, which is not compromised and perfectly works.

Not sure what to do.

I tried to find my FB ID (got it), and FB Token Access, but I think I don't manage to get the good FB Token Access since trying the tool this way actually bugs on 'Create New Account'.

Thanks very much for the help,

**Comment by Kyuuza** [comment]
@zalibi yeap for jp you have to rework the code a bit for the dataextractor same goes for global but not as extensive as jp

**Comment by Orionstar1988** [comment]
@killer66 what was the fix for "F_SUBLIMATTION_RECIPE_MST"?

**Comment by Killer66** [comment]
@Orionstar1988 

Just updated app, mst and rsc version. Oh, and the build as well.

On Bravehaxvius.cs:

Lines 16, 17, 18:
public String AppVersion { get; set; } = "1034";
public String RscVersion { get; set; } = "0";
public String MstVersion { get; set; } = "1102";

line 25:
public String BuildVersion { get { return Locale == "JP" ? "ver.2.9.3" : "ver.2.5.1"; } }

**Comment by Orionstar1988** [comment]
Hello all I was wondering for the JP Summon opton does it only do 1 per ticket? or is there a way to increase number of summons for each individual ticket?

I also ran into a issue where Im getting either "failed to get player name" when I try to inject items/materia or "please login again" error when trying to use my summon ticketson JP 

also @Killer66 thank you for the help :)

Also Happy Holidays to everyone :D

**Comment by zalibi** [comment]
What else would I need to change?

**Comment by Tifw** [comment]
I keep running to the same error, i already made the changes you suggested @Killer66 but with no success.
I changed the lines, runned the dataextractor and still can't pass the "Get Userinfo". It's for sure because i have a few new Units.
Btw: I'm a Brazillian user, if someone can talk portuguese with me in some private chat i would appreciate alot. And Happy Holidays to everyone <3
![hdjyekapqlak4f0jarxwrw](https://user-images.githubusercontent.com/34791539/34358054-ff2d3ca2-ea2a-11e7-925a-b05525ed04e5.png)
![z6mstvzbrjstuftynquc8g](https://user-images.githubusercontent.com/34791539/34358056-009b054c-ea2b-11e7-89e7-18d47bf46046.png)

**Comment by Cybotor** [comment]
@Tifw error is from you have unit that not have data on units.cs
solve by
1. run data extractor till your units.cs is complete update
or
2. remove new unit from your party (all party, arena etc)

**Comment by Tifw** [comment]
Just to be sure i'm doing right, how should i run the Data Extractor?

**Comment by Killer66** [comment]
@Cybotor , I think removing new units from party is not enough (tried this when this error was tormenting me and the error persists).
@Tifw , I have runned data extractor now in a old instance of the bot (with a outdated unit.cs file) and no sucess. Maybe the data extractor aren't working well or something... Tell me the size of your file, maybe I can give you the lines your is missing.

**Comment by Tifw** [comment]
@Killer66  Which file size? From the actual program or the data extractor? (Or it's the line size? Idk, sorry for me being so useless at this x.x)

**Comment by Killer66** [comment]
Units.cs

**Comment by Tifw** [comment]
![wigjsipkqp_kjf8mmydlsg](https://user-images.githubusercontent.com/34791539/34363394-8234db76-ea5a-11e7-8c9f-8dd6786c802a.png)

**Comment by Killer66** [comment]
As I expected. 

(I can't upload .cs files for some reason so you can just copy and paste)

[units.txt](https://github.com/shalzuth/BraveHaxvius/files/1587795/units.txt)

**Comment by Tifw** [comment]
@Killer66 Thank You so much! Everything working just fine now.

**Comment by Killer66** [comment]
@Tifw , I'm glad to help, enjoy o/

**Comment by Orionstar1988** [comment]
Hello again, I seem to be having trouble running the party lvling bot for JP every time I do so I get error for line 

#1196 var needsLeveling = !units.All(u => u.Level == u.UnitMaxLevel && u.Rarity == Unit.Units.FindAll(u2 => u.BaseUnitId == u2.BaseUnitId).Max(u2 => int.Parse(u2.Rarity)).ToString());

  " An unhandled exception of type 'System.NullReferenceException' occurred in BraveHaxvius.dll" 

then it crashed any suggestions? I also tried to update for JP items and units but extractor isnt working my Unit.cs size is 840 kb

**Comment by Cybotor** [comment]
@Orionstar1988 your error same with @Tifw 
You have unit that not have data on units.cs
You can bring @Killer66 file to use.
But if you have 7-star unit, there're no data on that file. Then error still occur.

**Comment by longst12a1** [comment]
Can you teach me how to add new tmr and stmr code in jp? 
@Killer66

**Comment by Killer66** [comment]
Hi @longst12a1 . Unfortunately I don't know how the JP process works, but in GL, for getting the codes of any new content, you have to update the versions of app, rsc and mst (and maybe the build version too) then run the DataExtractor.

**Comment by acexdt** [comment]
What's the new update for jp? sry, i don't know how to find it using android. :( can someone teach me?

**Comment by dsagaria** [comment]
Sorry guys, I can not do the update ... and what I have here does not work anymore, can someone make the program up to date? Thanks in advance.

**Comment by Killer66** [comment]
@dsagaria , what error you're getting?

**Comment by Ondraya** [comment]
Yeah, someone that has it working for Global, can you post a version so I can see if there are errors on my end and/or update my own file? It would be MUCH appreciated.

**Comment by Killer66** [comment]
I have posted my units file (updated) and the app, rsc and mst versions in a anterior comment.

**Comment by acexdt** [comment]
What's the new update for jp? sry, i don't know how to find it using android. :( can someone teach me?

**Comment by HotMoogle** [comment]
lol guys seriously everything is here don't leech and ask to upload a working tool :( 
GL BuildVer 2.5.1
AppVer 1034
RSC 0
MST 1102

**Comment by Ondraya** [comment]
I’m not trying to leech. I’m just REALLY new to coding programs and I get so many errors that Even when I get a part of it working, the majority doesn’t. I want to tmr farm and level and I can’t get my build stable.

**Comment by HotMoogle** [comment]
@Ondraya  read up your questions were already asked here thank you

**Comment by Ondraya** [comment]
Problem Event Name:	CLR20r3
  Problem Signature 01:	BraveHaxvius.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5a463576
  Problem Signature 04:	BraveHaxvius
  Problem Signature 05:	1.0.0.0
  Problem Signature 06:	5a463572
  Problem Signature 07:	89
  Problem Signature 08:	35f
  Problem Signature 09:	System.Exception
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789


I still get this at createuser.  What am I missing?  is this still a .net framework problem?

UPDATE:  I have found that it cannot find my user name despite having my correct token.  Is there more rewriting that I need to do to make it find it?

**Comment by ggwpx** [comment]
@Ondraya did you input GID, GTK, ID, PW, FB and FPW correctly?

**Comment by Cybotor** [comment]
@Ondraya 
error on CreateUser function, possible from your "unit.cs" file is not fully update.
and you have unit that not have data on "unit.cs" then this error is happen.

**Comment by Ondraya** [comment]
I copied in the new unit data. The newest unit I have is Cloud. 

I use the 00000-000-etc. for my device and my FB token like I used to back in September but now I get nowhere. I never needed to fill in the 2nd row with anything. Has that changed?

I re-installed framework, used the extractor, put in the new numbers. 

The crash report is just too generic for me to figure out my problem.

**Comment by Cybotor** [comment]
@Ondraya  try run program via debug on visual studio.
when you got error, it will show more error details where is incorrect point.
(same as @Tifw show on above reply)

and I may can tell you where is the problem.

**Comment by acexdt** [comment]
@Cybotor Master...may I has new JP versions? Thank you. Also, may I know how to get these if I use android?

**Comment by Cybotor** [comment]
AppVersion = "1034";
RscVersion = "737";
MstVersion = "2169";

**Comment by acexdt** [comment]
Thank you. :)

**Comment by Ondraya** [comment]
@Cybotor Like I said, I'm new to this so if I run a Debug on the .Exe, it does nothing and if I start it on the solution I get:
![vsdebug](https://user-images.githubusercontent.com/33197623/34454495-ab99c3ea-ed3a-11e7-8c68-be400839a7c2.jpg)



Also, I would be more than happy to carry this convo into a private chat so as not to destroy this string.

**Comment by ggwpx** [comment]
@Ondraya 
<img width="960" alt="right click" src="https://user-images.githubusercontent.com/33945641/34454950-6dcce9c6-ed43-11e7-87dc-f051335b77f0.PNG">

select set as startup project

**Comment by ggwpx** [comment]
Does anyone know the correct server for JP data extractor? 
 datContent = Downloader.DownloadString("http://lapis-dlc.gumi.sg/dlc_assets_prod/" + loc + "/Ver" + version + "_" + nameKey["Name"] + ".dat");

I don't think the server is http://lapis-dlc.gumi.sg/dlc_assets_prod but something new.

**Comment by Cybotor** [comment]
http://cdn.resource.exvius.com/lapis/resource/

**Comment by ggwpx** [comment]
<img width="960" alt="uhh" src="https://user-images.githubusercontent.com/33945641/34459748-4c1873a2-edc7-11e7-94f8-a927fb67adb4.PNG">
I changed the address... but the error. I only extracted Sublimation.cs, GameObject.cs, Request.cs and Variable.cs

**Comment by Ondraya** [comment]
public String Device { get; set; } = "iPhone9,3";

is that accurate for line 19 of the BraveHaxvius.cs?

**Comment by dsagaria** [comment]
Hello friends, I try to update my program with the instructions given by you but I'm not succeed ... but I still use this version, https://drive.google.com/open?id=1R2glEBV-nfKnBij8O2MdE9F_27edLttb, which works until today, however not with new units. So I would like to ask you, if any of you can update it and send me back, I would be very grateful !!

**Comment by Killer66** [comment]
@dsagaria , I have posted a updated units.cs file in this thread. Just copy the content of the txt file and paste on your units.cs file. This should solve your problem.

**Comment by Ondraya** [comment]
Woah, that interface is so different from what I have. What info do I need to have to use it? It’s probably why I can’t get it to work. I have an old build.

**Comment by HotMoogle** [comment]
@dsagaria kindly delete links thanks else open up a new topic

**Comment by HotMoogle** [comment]
Anyways Closing this thread as people keep on uploading and posting working files which we are avoiding because of spies and gimu employees kindly create a new thread for updates in the future. Thank you all who participated on my thread.

**Comment by HotMoogle** [comment]
re-opening the thread.. please dont upload or talk in private ( if you want to share the compiled tool)

**Comment by Killer66** [comment]
@HotMoogle 
Noob question: Github have pvt chat? I know that in the past it had.

**Comment by dsagaria** [comment]
Sorry about my mistake...
I like if someone make a more complete tutorial about how to update the tool... I try sometimes but without success...

**Comment by Ondraya** [comment]
I have completely failed. I’m the special child that needs the step by step process in this case so I will stop asking and just do more reading.

**Comment by HotMoogle** [comment]
@dsagaria @Ondraya  ok pm me in discord ill give you the updated tool after maintenance this should only be once
look for Effigy

**Comment by Rezzk** [comment]
Looks like none of the version info has changed after maintenance.

**Comment by HotMoogle** [comment]
appver1035 rsc 0  mst 1111  
GLobal

**Comment by Tifw** [comment]
Guys, i'm having that problem where my unit.cs don't have the units from the new banner and because of that i can't use the program. Can someone help me?

**Comment by ggwpx** [comment]
@Tifw run the data extractor

**Comment by Tifw** [comment]
@ggwpx by some reason unknown my Data Extractor is not working.

**Comment by robidk** [comment]
@Tifw  by default the data extractor is looking for the BraveHaxvius/.. Directory to write to but if you downloaded the version from here it would have been named like BraveHaxvius-Master . This is the issue I was having, you have to either rename your folder to match whats in the dataextractor or modify the data extractor code. Thats what happened to me anyway. Hope it helps!

**Comment by NeoTetsuya** [comment]
Do anyone have the code for the auto clear raid? My button seems like grey all the time.

**Comment by ggwpx** [comment]
@NeoTetsuya 

        public void ClearRaid()
        {
            var orbs = UInt16.Parse(GetUserInfo[GameObject.UserTeamInfo][0][Variable.RaidOrb].ToString());
            while (orbs > 0)
            {
                var RoutineRaidMenuUpdate = Network.SendPacket(Request.RoutineRaidMenuUpdate,
                    new JProperty(Variable.RoutineRaidMenuUpdate, new JArray(new JObject(
                            new JProperty(Variable.DungeonId, Mission.ConquerorofIzanderELT.MissionId.Substring(0, Mission.ConquerorofIzanderELT.MissionId.Length - 2))))));
                var missionResult = DoMission(Mission.ConquerorofIzanderELT, true, null, null, null, false, false, false, false, false, null, 15000);
                orbs = UInt16.Parse(missionResult[GameObject.UserTeamInfo][0][Variable.RaidOrb].ToString());

                var ItemDad = missionResult[GameObject.UserItemInfo_4pYnBMw7];
                if (ItemDad != null)
                {
                    String SS = missionResult[GameObject.MissionResult][0]["Vy9YXBE7"].ToString();
                    Logger.Out(String.Format("--->Total Item : {2}:{1} -> {0}", Item.Items.First(i => i.ItemId == ItemDad[0][Variable.ItemId].ToString()).Name, ItemDad[0][Variable.ItemCount].ToString(), SS.Substring(SS.LastIndexOf(":") + 1)));
                }
                Thread.Sleep(100);
            }
        }

**Comment by ggwpx** [comment]
@Tifw 
[unit.txt](https://github.com/shalzuth/BraveHaxvius/files/1610469/unit.txt)
rename it to unit.cs

**Comment by NeoTetsuya** [comment]
![image](https://user-images.githubusercontent.com/35198449/34657139-ea6f0c8e-f455-11e7-8ab1-da3626e0fb27.png)
@ggwpx idk why i cant click this button despite using ur codes.

**Comment by ggwpx** [comment]
you supposed to click the "do raid" <img width="579" alt="doraid" src="https://user-images.githubusercontent.com/33945641/34657184-d2aa5fa4-f3f1-11e7-9082-17b4e827698e.PNG">

**Comment by NeoTetsuya** [comment]
@ggwpx  ohh okay, i think i can use that auto clear raid for convenience.

**Comment by Tifw** [comment]
@robidk i renamed it but no change.
@ggwp it's already unit.cs

Maybe it's a problem with my data extractor :/ idk.

**Comment by ark84** [comment]
Does anyone have the new "appver rsc mst" for JPver ? Please share, ty.

**Comment by Cybotor** [comment]
AppVersion = "1034";
RscVersion = "740";
MstVersion = "2172";

**Comment by smithd4200** [comment]
@ggwpx can you contact me on discord?  I'm curious about a couple of things in that screenshot.

Thanks
smithd4200

**Comment by ggwpx** [comment]
@smithd4200 dont have discord

**Comment by ark84** [comment]
@Cybotor  Could you share the new JP update values again ? tyvm.

**Comment by Zharion12** [comment]
@ggwpx Hi, I wanted to ask how I can have that tool that you have? since I have the old one and do not have so many buttons to complete missions?

**Comment by Cybotor** [comment]
AppVersion = "1034";
RscVersion = "747";
MstVersion = "2201";

**Comment by acexdt** [comment]
Thank you.

**Comment by Killer66** [comment]
Any changes on the GL version?

**Comment by Zharion12** [comment]
What are the new values for the GL version?

**Comment by Killer66** [comment]
@Cybotor , do you have the new values of GL? (if they changed at all)

**Comment by Cronofei** [comment]
Anyone know what OperatingSystem value to use for hitting the ONE Store?

**Comment by ggwpx** [comment]
GL 
public String AppVersion { get; set; } = "1035;
 public String RscVersion { get; set; } = "0";
 public String MstVersion { get; set; } = "1122";

**Comment by Monqui001** [comment]
![image](https://user-images.githubusercontent.com/35425869/34917576-9fdc1dd6-f948-11e7-834c-0c88a4fc6acd.png)
 got this anyone can help? did all build rebuild etc

**Comment by ark84** [comment]
Did they patch the tool on JP ? Can't login to the JP server.

**Comment by Cybotor** [comment]
@ark84  mst change to 2204

**Comment by ark84** [comment]
tyvm, so you can't use the old values to login anymore.

**Comment by HotMoogle** [comment]
mst 1131

**Comment by DregonYor** [comment]
could someone give me the code to add MY ID so that i can use the Use even friend? thanks

**Comment by dsagaria** [comment]
could someone send to me a invite to Discord?

**Comment by Cybotor** [comment]
https://discord.gg/799qSNR

**Comment by dsagaria** [comment]
Thanks!!

**Comment by acexdt** [comment]
anyone has the new versions for JP? please and thank you.

**Comment by acexdt** [comment]
@Cybotor Master, sho us da wae (versions) to Valkyrie Profile. Please. Thank You very very much.

**Comment by shalzuth** [comment]
Feel free to submit a pull request to update the versions, anyone.

**Comment by Cybotor** [comment]
for JP
AppVersion = "1035";
RscVersion = "755";
MstVersion = "2224";

**Comment by Killer66** [comment]
New versions?

**Comment by Zharion12** [comment]
Do you know what are the mst values of the GL version?

**Comment by Ondraya** [comment]
GL
AV 1036
RscV 0
MstV 1147

**Comment by Kyuuza** [comment]
anyone willing to share the updated tool source which is mentioned above with me?

**Comment by Ondraya** [comment]
Try the Discord group, more MIGHt be available there

**Comment by Kyuuza** [comment]
tried so far no luck,thanks for the pointer

**Comment by sky1206** [comment]
anyone has the new versions for JP? Tifa is out!! My sincere thanks.

**Comment by HotMoogle** [comment]
@Ondraya  so glad your tool is working great now :)

**Comment by Ondraya** [comment]
@HotMoogle thanks, I just needed someone to double check my steps to get it there.  Is there anyone that has panel set up to do multiple DIFFERENT missions in a loop that would be willing to talk (like a layman) about HOW it was set up?  No code, I just need to know what connections I need to make it work. Is it ok for me to post an email address for that?

**Comment by sky1206** [comment]
anyone has the new versions for JP? Tifa is out!! My sincere thanks.

**Comment by donradzsk** [comment]
And for global too.

Also does anyone know what the syntax for lb gain is? Right now it's set to null
(false, null, null, null, false, false, false, false, false, **null**, 50000)
but I would like to set it to at least 1.

**Comment by Cronofei** [comment]
For Global:
  AppVersion 1036
  RscVersion 0
  MstVersion 1164

If you check my fork I've modified the code to read versions from the config file, and log them and update it when they change.

**Comment by acexdt** [comment]
@Cronofei do you know the jp versions? Thank you.

**Comment by Cybotor** [comment]
for JP
AppVersion = "1035";
RscVersion = "766";
MstVersion = "2263";

**Comment by sky1206** [comment]
@Cybotor Thank you! I just (now) learned how to search for them! I will update it next time. haha

**Comment by Cronofei** [comment]
Does anyone know how to get the basic repeat mission working? When I try it seems to force a re-login a lot of the time.

**Comment by donradzsk** [comment]
Okay so I've spent the past few days researching and figured out the syntax for adding items:

b.DoMission(Mission.AirshipDeck, false, null, "21:" + Equipment.GenjiGlove.EquipId + ":2", null, false, false, false, false, false, **null**, 50000);

But of course it's not working. So what would be the syntax for LB experience (the null before 50000 above)? @ggwpx or anyone more knowledgeable? I'm learning and doing it manually in Visual Studio.

**Comment by sky1206** [comment]
Update:
JP
AppVersion = "1036";
RscVersion = "776";
MstVersion = "2315";

Global
1037
0
1182

Correct me if I'm wrong. 1st time checking these on my own,

**Comment by Cronofei** [comment]
Anyone know how to use the bot to restore energy?

**Comment by Cronofei** [comment]
@donradzsk I believe you just type in how much LB experience you want, as a string. IE, if you want to gain 10 LB Xp, type "10" (include the quotes);

**Comment by JunkyardCat** [comment]
does anyone know the new version number for gl?

**Comment by Killer66** [comment]
@JunkyardCat 

App Global:
1037
Rsc:
0
Mst:
1182

**Comment by JunkyardCat** [comment]
@Killer66 
nope the app updated just recently around an hour ago. it downloaded some things so the version must have changed. 

Note I am already using that version

**Comment by sky1206** [comment]
MST: 1185

**Comment by donradzsk** [comment]
Mst for global changed again?

@Cronofei thanks, I had figured it out through trial and error.

**Comment by Killer66** [comment]
DataExtractor unable to att the data due to the IOS issue?

**Comment by Leon1080** [comment]
@Cybotor 
New update JP?
AppVersion , RscVersion , MstVersion

**Comment by sky1206** [comment]
Locale = "JP";
AppVersion = "1036";
RscVersion = "797";
MstVersion = "2436";

The JP summon does not work though (everything else works the same). Hope someone can shed some light into this. Thank you.
P.S. someone already created a thread regarding this.

**Comment by JunkyardCat** [comment]
whats the app rsc and mst version for the GL

**Comment by Ondraya** [comment]
I can't figure out the new numbers for GL.  How do I do that with the dataextractor?

**Comment by HotMoogle** [comment]
Error as of the moment:

System.IndexOutOfRangeException
  HResult=0x80131508
  **Message=Index was outside the bounds of the array.**
  Source=DataExtractor
  StackTrace:
   at DataExtractor.Program.<>c__DisplayClass17_2.<DumpTranslation>b__3(String m) in C:\Users\User\Desktop\s\BraveHaxvius\DataExtractor\Program.cs:line 284
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at DataExtractor.Program.DumpTranslation(List`1 translations, List`1 json, String translation, String mst, String className, Dictionary`2 members) in C:\Users\User\Desktop\s\BraveHaxvius\DataExtractor\Program.cs:line 284
   at DataExtractor.Program.DumpTranslation(JToken msts, String translation, String mst, String className, Dictionary`2 members) in C:\Users\User\Desktop\s\BraveHaxvius\DataExtractor\Program.cs:line 240
   at DataExtractor.Program.Main(String[] args) in C:\Users\User\Desktop\s\BraveHaxvius\DataExtractor\Program.cs:line 384

**Comment by Oligram** [comment]
Any fix for DataExtractor? (GL)

**Comment by HotMoogle** [comment]
You need to wait for gumi to fix the leviathan loop issue this will fix the problem
