### ISSUE TITLE
Crashed upon running missions

### ISSUE THREAD

**Issue by mrbojoa** [shalzuth/BraveHaxvius#53]
Is anyone facing the same issue with v1.0.37 release? How do i go around to fix it?

Thanks!

**Comment by HotMoogle** [comment]
#52

**Comment by mrbojoa** [comment]
@HotMoogle resolved, thanks :)

**Comment by HotMoogle** [comment]
download VS 2017 community edition. open solution
update which is indicated above! this thread :)

**Comment by mrbojoa** [comment]
@HotMoogle resolved, thanks :)
