### ISSUE TITLE
Facebook two factor authorization

### ISSUE THREAD

**Issue by Orionstar1988** [shalzuth/BraveHaxvius#56]
Hello I keep running into a issue with line #82 in the facebook.cs apparently the two factor authorization isnt working and causing facebook to block the account before it could get in. please help?

**Comment by Bazuzko** [comment]
I have suddenly the same issue.

But I don't use the two-factor authorisation and never have.

The only things that changed since I had this problem suddenly appear are:
- Updating the tool (APP/MST/Build, + DataExtractor)
- Change continent for the holidays
