### ISSUE TITLE
Big fart for @Willowed

### ISSUE THREAD

**Issue by fantasyste** [shalzuth/BraveHaxvius#60]
What can be done with Nox and nacros? Willowed i love you :)
Metalsred and willowed now observed in-game

**Comment by Killer66** [comment]
Hello and welcome! I think the only thing you can do on GL version for now is farming (tmr, xp and so on).

**Comment by fantasyste** [comment]
Not manually inject stuff?

**Comment by Killer66** [comment]
Not in the GL version.

**Comment by fantasyste** [comment]
Where can i contact you @Killer66 for setting the app up? I would love to try this on JP, then.

**Comment by fantasyste** [comment]
https://www.epicnpc.com/threads/1036048-FFBE-Injection-amp-Summoning-Service-GL-JPN

How this guy can inject in GL if it s not possible to ?

**Comment by Killer66** [comment]
@fantasyste 
 If you at least read the comments of the link you posted you will see that he doesn't.

**Comment by Killer66** [comment]
But, if he do, you can ask him, because I really don't know.

**Comment by Killer66** [comment]
Oh, and for the use of this tool on JP, I really don't know, I use only on GL.

**Comment by fantasyste** [comment]
Mainly for which uses, you use it in GL? @Killer66 i m gonna ask (introducing myself as Gumi agent :D )

**Comment by Killer66** [comment]
Oh, you're a gumi agent? Oh my god, excuse me but now I'll run in fear.

**Comment by fantasyste** [comment]
You dont understand @Killer66. 
I m gonna contact him by assuming that i m working for Gumi, so i can obtain info
