### ISSUE TITLE
Display TMR percentage

### ISSUE THREAD

**Issue by jash1412** [shalzuth/BraveHaxvius#61]
Is it possible to code the program to display the TMR percentage? If yes, can someone guide me on how to modify it?

I think this would be helpful to everybody so we do not need to login to the game to check on the progress.

Thanks in advanced.

**Comment by Killer66** [comment]
Well, this would be a great addition.

**Comment by Cybotor** [comment]
below is function to retrieve current party information.
method is.
1. get current party information.
2. call UpdateUnits for update units information to made comparison
3. units variable will contain all Party informaion
4. retrieve unit name & TMR to show

output is string variable that contain unit information (1 line per unit)
call this function to show on Form's text label.

-------------------------------------------------------------- 
        public string GetCurrentPTdeck()
        { 
            var currentParty = int.Parse(GetUserInfo[GameObject.UserActualInfo].First()[Variable.CurrentParty].ToString());
            var party = GetUserInfo[GameObject.UserPartyDeckInfo_5Eb0Rig6][currentParty];
            var partyUnits = party[Variable.PartyUnits].ToString().Split(new char[1] { ',' });
            UpdateUnits();
            var units = partyUnits.Select(u => Units.FirstOrDefault(unit => unit.UniqueUnitId == u.Split(new char[1] { ':' }).Last())).ToList();

            var PDeck = "";
            foreach (var a in units)
            {
                PDeck += a.Name + "(" + a.Tmr + "%)\r\n";
            }
            return PDeck;
        }

**Comment by Killer66** [comment]
@Cybotor , this function goes on the BraveExvius.cs file?

**Comment by Cybotor** [comment]
@Killer66  Yes.

to use this function, I create label object "PTlabel" on form.
and call function on click event for login button.

PTlabel.Text = client.GetCurrentPTdeck();

**Comment by Killer66** [comment]
@Cybotor , Alright, I will try to figure out how to do this (I'm really noob at this). Thanks for the response.
