### ISSUE TITLE
App, rsc and mst new values (GL)? 

### ISSUE THREAD

**Issue by Killer66** [shalzuth/BraveHaxvius#65]
Anyone have the new values form GL version?

**Comment by Cronofei** [comment]
public String AppVersion { get; set; } = "1035";
        public String RscVersion { get; set; } = "0";
        public String MstVersion { get; set; } = "1122";

If you know how to debug, breakpoint the function BraveExvius::Initialize()

ie, find this line in BraveExvius.cs : public void Initialize()

If the MST version is wrong, you'll see it hit this line when debugging.

MstVersion = (initialiseResponseData[GameObject.VersionInfo].First(f => f[Variable.KeyName].ToString() == "F_MST_VERSION"))[Variable.Value].ToString();

That variable will get assigned the new value. If AppVersion (or RscVersion) change, you can do similar by debugging the code that is similar for them.

In fact you could just Logger.Out the values if you don't want to debug, and then just watch the console.

**Comment by Killer66** [comment]
Wow, that's helpful, thank you. I will try to figure out how to do this.
