### ISSUE TITLE
Data Extractor

### ISSUE THREAD

**Issue by HistoreLaw** [shalzuth/BraveHaxvius#68]
No se pudo ejecutar la compilación Compilar.

Sorry i'm spanish speaker

**Comment by ghost** [comment]
@HistoreLaw `Install-Package Newtonsoft.Json`

**Comment by newChallenger1** [comment]
anyone get IP banned by using this tools ? somehow I cannot login, and it says blocked by server or something. maybe because doing missions too fast.. if anyone experienced this, how long will it take to normally login again?
