### ISSUE TITLE
The remote name could not be resolved: 'lapisv240.gumi.sg'

### ISSUE THREAD

**Issue by newChallenger1** [shalzuth/BraveHaxvius#71]
When it happen, I changed the address 'lapisv240.gumi.sg' to something I found in internet.. and now it's working again..
Anyone can teach me how to do it with Fiddler ? The address never shown in Fiddler (only Facebook stuff).. I'm using Android btw.. Any help will be appreciated.. Thanks in advance

**Comment by tyasa81** [comment]
Hi. Can you or anyone else pls let me know whats the new address? It has changed from lapisv240.
