### ISSUE TITLE
DataExtractor problem

### ISSUE THREAD

**Issue by Killer66** [shalzuth/BraveHaxvius#72]
DataExtractor unable to att the data due to the IOS issue?

**Comment by robidk** [comment]
After today's update getting error message, http://lapis-dlc.gumi.sg/dlc_assets_prod/ has changed? Anyone know what is new location?

**Comment by lupier** [comment]
This is not a problem at all, always use packet decoder for research with your mobile device and proxy

**Comment by Mikeo73** [comment]
has anyone been able to update recently? I have been getting errors. 
If so, can you share your mission file with me?

**Comment by lupier** [comment]
[Mission.zip](https://github.com/shalzuth/BraveHaxvius/files/2363943/Mission.zip)
