### ISSUE TITLE
Can you upload BraveHaxvius that works?

### ISSUE THREAD

**Issue by ghost** [shalzuth/BraveHaxvius#75]
Version1.0.37's BraveHaxvius does not work well. 
Can you upload BraveHaxvius that works?

**Comment by Leon1080** [comment]
Which function not work?
GB or JP?

**Comment by ghost** [comment]
all don't work. it's jp version.

**Comment by ghost** [comment]
An error is displayed for all actions, and the program terminates forcibly.

**Comment by Leon1080** [comment]
jp still work with injection

**Comment by ghost** [comment]
Can I use files that can be downloaded from here without changing anything?
I always forced termination when I enter TrancferCode and TrancferPin and click on LevelTab's LevelParty.
https://github.com/shalzuth/BraveHaxvius/releases

**Comment by Leon1080** [comment]
Ignore all, You just login and use inject

**Comment by ghost** [comment]
I tried only the injection, but it was forced to quit.

**Comment by newChallenger1** [comment]
never played JP before, is summon ticket or 10+1 summon ticket still injectable ?

**Comment by ghost** [comment]
can't inject.If you attempt to log in, an error will be displayed.

**Comment by newChallenger1** [comment]
Hey, I can inject EX ticket that get Madiena or Loren.. Any other ticket that works ?

**Comment by jokersell** [comment]
@Leon1080  could you update the BraveHaxvius to new ver? 1.0.37 is not use

**Comment by lupier** [comment]
Hi ALL!
Current url in Networking.cs SendPacket - https://v270lapisdtz9oirblf.gumi.sg/lapisProd/app/php/gme/actionSymbol/
app version - 1041
rsc - 0
mst - 1263
BuildVersion global "ver.2.7.3"
