### ISSUE TITLE
[FFBE-JP] Summon Ticket Injection

### ISSUE THREAD

**Issue by newChallenger1** [shalzuth/BraveHaxvius#76]
10+1 and Summon Ticket ARE NOT INJECTABLE.
EX (Loren, Mediena) Ticket and FEB Ticket (Xenogears event) ARE INJECTABLE.

**Comment by jokersell** [comment]
@newChallenger1 the ffbe injection tool 1.0.37 is not work now  ,  could you update it ?

**Comment by jokersell** [comment]
i want to buy the ffbe injection tool if you sell it please reply to me  @newChallenger1

**Comment by newChallenger1** [comment]
@jokersell your private email address maybe or any chatting app ID? For easier contact purpose..

**Comment by jokersell** [comment]
@newChallenger1   my email is 2296713829@qq.com

**Comment by newChallenger1** [comment]
@jokersell I have sent you email, check it

**Comment by mmoore5325** [comment]
Uokingbritish@gmail.com - hit me up as well if you don't mind.

**Comment by Egorgian** [comment]
I am interested as well, jcshank058@gmail.com

**Comment by omnee** [comment]
Email me aswell please... omneekun@gmail.com

**Comment by newChallenger1** [comment]
Done, check your email

**Comment by zikaru1** [comment]
intrested as well ! email me please :D    neo_lyh@hotmail.com

**Comment by newChallenger1** [comment]
Done, check email

**Comment by newChallenger1** [comment]
gonna close this

> ```10+1 and Summon Ticket ARE NOT INJECTABLE.
> EX (Loren, Mediena) Ticket and FEB Ticket (Xenogears event) ARE INJECTABLE.```

chat me at discord, newChallenger#2241
