### ISSUE TITLE
how to update the item list ? could someone help me?  if you tell me or help me do this i'm glad to pay it

### ISSUE THREAD

**Issue by jokersell** [shalzuth/BraveHaxvius#81]
@shalzuth or anyone who can help me

**Comment by lupier** [comment]
Use DataExtractor

**Comment by jokersell** [comment]
@lupier could you help me to update the list ? i can pay some money to you  thanks

**Comment by jokersell** [comment]
@lupier　my email is 2296713829@qq.com could you help me to update the jp list? thanks

**Comment by jokersell** [comment]
@Cybotor  hello， could you help me to update the jp list? (ffbe injection tool) ,or maybe you can tell me how to update it ? thanks , my email is 2296713829@qq.com i can pay some money for your help
