### ISSUE TITLE
Please give me a tool that can inject items.

### ISSUE THREAD

**Issue by ghost** [shalzuth/BraveHaxvius#83]
I can prepare the money.
I'm happy to tell you how to update the tool.
I will be waiting for your reply.

**Comment by ghost** [comment]
Additional notes
Version is Japan.

**Comment by newChallenger1** [comment]
you can chat me at discord
newChallenger#2241

**Comment by ghost** [comment]
I sent you friend request

**Comment by ghost** [comment]
thank you
