### ISSUE TITLE
LB error

### ISSUE THREAD

**Issue by ghost** [shalzuth/BraveHaxvius#87]
Good afternoon everybody.
I am suffering about "LB" now.
If I enter a value in "LB" of the "Missions" tab now, the tool will be forcibly terminated.
I think that the LB code is around here, but I do not know how to improve it.
I'm happy if you give me advice, I will wait for your reply.

            var lbTotal = 1;

            if (!String.IsNullOrEmpty(lbIncrease) && !getTrophies)
            {
                var lbVal = Int32.Parse(lbIncrease);
                var currentParty = int.Parse(GetUserInfo[GameObject.UserActualInfo].First()[Variable.CurrentParty].ToString());
                var party = GetUserInfo[GameObject.UserPartyDeckInfo_5Eb0Rig6][currentParty];
                var partyUnits = party[Variable.PartyUnits].ToString().Split(new char[1] { ',' });
                var units = partyUnits.Select(u => Units.FirstOrDefault(unit => unit.UniqueUnitId == u.Split(new char[1] { ':' }).Last())).ToList();
                var unitLimit = String.Join(",", units.Select(u => u.UniqueUnitId + ":" + lbIncrease));
                lbTotal = 0;
                units.ForEach(u => lbTotal += lbVal);
                MissionResult.Add(Variable.LBExperience, unitLimit);
            }

**Comment by daysleeper7** [comment]
Can you provide your solution? I have the same problem.

**Comment by lupier** [comment]
Let me explain why you get some error. Outdated units list. **Always** use data extractor with latest app, mst values before creating any kind of new issue.
p.s. if you want to get some support - explain technical details about error from visual studio. You must understand "omg, I've got some horrible error" isn't technical description about your situation.
