### ISSUE TITLE
Bot unable to connect to server

### ISSUE THREAD

**Issue by Killer66** [shalzuth/BraveHaxvius#91]
Any thoughts?

**Comment by Killer66** [comment]
Solved!

**Comment by lastprimedev** [comment]
@Killer66 What do you do to fix it? Thanks.

**Comment by Killer66** [comment]
https://github.com/shalzuth/BraveHaxvius/issues/85

See comment number 6# from Iupiter.

**Comment by lastprimedev** [comment]
@Killer66 Got it. Thanks a lot.

**Comment by ActalNufofen** [comment]
Hi @Killer66, @lastprimedev 

I am getting Error 500. Any idea how can I fix this? thanks. 
Exception thrown: 'System.Net.WebException' in System.dll
Error : The remote server returned an error: (500) Internal Server Error.

![image](https://user-images.githubusercontent.com/34798188/45598449-f0f9a080-ba0e-11e8-9069-9aa5d79b4b67.png)

**Comment by lupier** [comment]
> Error : The remote server returned an error: (500) Internal Server Error.
Check URL in SendPacket function from Networking.cs
current url `https://lapis310nRdM8OKpzHLOlZ42.gumi.sg/lapisProd/app/php/gme/actionSymbol/`
