### ISSUE TITLE
How to use the IDA Scripts in order to update keys ?

### ISSUE THREAD

**Issue by Cedraow** [shalzuth/BraveHaxvius#96]
Hi everyone,

I wanna update the json files in the DataExtractor folder (like https://github.com/shalzuth/BraveHaxvius/blob/master/DataExtractor/network.json) : I launch the scripts in IDA Pro, but finally the generated json are empty (I use the libgame.so in "lib > x86").
(I use an previous version of the app binary, because newers are in x64)

Does somebody know why the generated json are empty ?

Many thanks for all the work done.

**Comment by lupier** [comment]
Just curious, why you need that file? Almost all requests are same. Few of them is new, but you always can extract it's names with fiddler web debugger.
So, my question is - why do you need that json file? What exactry you trying to do?

**Comment by Cedraow** [comment]
I'm trying to fix the friend selection before launching mission. So I've sniffed the package from the friend's selection screen, but there is a new id.
I could extract the id, it name and it key with Fiddler ?

**Comment by lupier** [comment]
Just open packetdecoder.exe, do one-two missions and select any "GetReinforcementInfo" packet and check it's json structure for new ideas

**Comment by Cedraow** [comment]
Indeed, it's easier ! :)
Many thanks for the advice
